import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({
  variable: "--font-inter",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
>>>>>>> 7ba1ff0f89e89f682581db305853f025c9a52648
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "CANTING - Dashboard UMKM Batik",
  description: "Sistem pengelolaan UMKM Batik Surabaya",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 7ba1ff0f89e89f682581db305853f025c9a52648
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
<<<<<<< HEAD
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-[#F8FAFB] text-[#1A2B2B]">
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-8 overflow-y-auto bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
=======
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
>>>>>>> 7ba1ff0f89e89f682581db305853f025c9a52648
